In [1]:
import numpy as np

In [7]:
# Basics #1 - Creating Numpy Array - 1D, 2D & 3D

list = [1,2,3,4,5,6,7,8,9,10,11,12]

arr1d = np.array(list)
print("One Dimention Array:\n",arr1d)

arr2d = np.array(list).reshape(2,6)
print("\nTwo Dimention Array:\n",arr2d)

arr3d = np.array(list).reshape(2,2,3)
print("\nThree Dimention Array:\n",arr3d)

One Dimention Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Two Dimention Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Three Dimention Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Note: Number of elements in the list and size of the array should match. If not, Numpy will raise an expection.

***

In [12]:
# Basics # 2 - Generation of Sequence Numbers

arr = np.arange(10)
print(arr)

arr = np.arange(11, 20)
print(arr)

arr = np.arange(21, 30, 2)
print(arr)

arr = np.arange(31, 40, 3, float)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[21 23 25 27 29]
[31. 34. 37.]


Syntax: ```np.arange([start], stop, [step], [dtype])```
* Returns an array with evenly spaced elements. 
* Starting number is optional, if not specified, range will start from Zero `0`.
* End of interval. The interval does not include this value. It means stop number not included in the list
* Step - Spacing between values. For any output out, this is the distance between two adjacent values. Default is 1.
* The data type of the output array.

In [14]:
# Basics #3 - Linear Space

arr = np.linspace(1,5)
print(arr)

arr = np.linspace(1,10, 5)
print("\n",arr)

arr = np.linspace(1,10, 5, endpoint=False)
print("\n",arr)

arr = np.linspace(1,10, 5, retstep=True)
print("\n",arr)

arr = np.linspace(1,10, 5, dtype=int)
print("\n",arr)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]

 [ 1.    3.25  5.5   7.75 10.  ]

 [1.  2.8 4.6 6.4 8.2]

 (array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

 [ 1  3  5  7 10]


Syntax: np.linspace(start, Stop, num)
* Default is float, generates 50 numbers default. 
* By specifing a value for `num` we generate the required numbers between the specified range
* endpoint parameter helps to include or exclude the stop number.
* retstep paramter helps to understand the step (difference between two numbers)
* dtype helps to define the data type.

In [30]:
# Basics #4 - Random number generation

arr = np.random.rand(2)
print(arr)

arr = np.random.rand(3,2)
print("\n",arr)

arr = np.random.rand(2, 3,2)
print("\n",arr)

arr = np.random.randn(5)
print("\n",arr)

arr = np.random.randint(10,20,5)
print("\n",arr)

arr = np.random.permutation(5)
print("\n",arr)

[0.19624107 0.12155322]

 [[0.86305809 0.27229147]
 [0.73745144 0.49776665]
 [0.78973373 0.99915473]]

 [[[0.96365008 0.43127251]
  [0.86486572 0.15588631]
  [0.17157989 0.88511554]]

 [[0.66785361 0.16924953]
  [0.13874827 0.23292534]
  [0.3011523  0.66067995]]]

 [-1.39492096 -1.52164959 -0.02640319  0.45648056 -0.31296286]

 [18 13 13 14 13]

 [1 2 3 4 0]
[1, 4, 5, 6, 7]


* `rand` - Genrates specified random number between 0 and 1. Default is 1D array, we can generate high dimention also./
* `randn` - Genrates a normal distribution numbers 
* `randint` - Number of integers between specified range