In [1]:
import numpy as np


----


# NumPy - Splitting Array

Splitting is reverse operation of Joining. Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits. The return value of the `array_split()` method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element.

In [14]:
# Split the array in 3 parts:
arr1 = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr1, 3)
print(split_arr,"\n")

print("Array 1:{}".format(split_arr[0]))
print("Array 1:{}".format(split_arr[1]))
print("Array 1:{}".format(split_arr[2]))

[array([1, 2]), array([3, 4]), array([5, 6])] 

Array 1:[1 2]
Array 1:[3 4]
Array 1:[5 6]


In [22]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

split_arr = np.array_split(arr1, 4)

print(split_arr)

for arr in split_arr:
    print("Array :{}".format(arr))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
Array :[1 2]
Array :[3 4]
Array :[5]
Array :[6]


>**Note:** We also have the method `split()` available but it will not adjust the elements when elements are less in source array for splitting like in example above, `array_split()` worked properly but `split()` would fail.

#### Splitting 2-D Array

In [44]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print("Array :\n{}".format(newarr[0]))
print("Array :\n{}".format(newarr[1]))
print("Array :\n{}".format(newarr[2]))

Array :
[[1 2]
 [3 4]]
Array :
[[5 6]
 [7 8]]
Array :
[[ 9 10]
 [11 12]]


In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 4)

print("Array :\n{}".format(newarr[0]))
print("Array :\n{}".format(newarr[1]))
print("Array :\n{}".format(newarr[2]))
print("Array :\n{}".format(newarr[3]))

Array :
[[1 2 3]
 [4 5 6]]
Array :
[[ 7  8  9]
 [10 11 12]]
Array :
[[13 14 15]]
Array :
[[16 17 18]]


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print("Array :\n{}".format(newarr[0]))
print("Array :\n{}".format(newarr[1]))
print("Array :\n{}".format(newarr[2]))



Array :
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Array :
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Array :
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


#### Splitting 2-D Array using hsplit()

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print("Array :\n{}".format(newarr[0]))
print("Array :\n{}".format(newarr[1]))
print("Array :\n{}".format(newarr[2]))

Array :
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Array :
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Array :
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


An alternate solution is using hsplit() opposite of hstack().

**Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().**


---
