
# Numpy - Indexing

## Indexing array

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

#### Negative Indexing
Use negative indexing to access an array from the end. -1 refers to the last element in the array.

## Slicing arrays

Slicing in python means taking elements from one given index to another given index.We pass slice instead of index like this: `[start:end]`.

We can also define the step, like this: `[start:end:step]`. If we don't pass start its considered `0`. If we don't pass end its considered `length of array` in that dimension. If we don't pass step its considered `1`


In [1]:
import numpy as np


****


In [2]:
# This is an example to create 3D array with data type

arr3d = np.array([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]
    ]
], dtype='int8')

print(arr3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]



***



## Numpy - Indexing


In [3]:
# Index the 3 from the array

print(arr3d[0,0,2])

3


In [4]:
# Index the 9 from the array

print(arr3d[0,1,3])
print(arr3d[0,1,-2])   # Using the negative index, last element is -1

9
9



## Numpy - Slicing


In [5]:
# Slice the 18 & 19 from the array
# Dimension: 1, Row: 1, Columns: 2 & 3. (4 Excluded)

print(arr3d[1,1,2:4])


[18 19]


In [6]:
# Slice the 2, 7, 12,& 17 from the array
# Dimension: All, Row: All, Columns: 1

print(arr3d[:,:,1])

[[ 2  7]
 [12 17]]


In [7]:
# Slice the 2,3 & 4 Colums from the array
# Dimension: All, Row: All, Columns: 1 to 3 (4 Excluded)

print(arr3d[:,:,1:4])

[[[ 2  3  4]
  [ 7  8  9]]

 [[12 13 14]
  [17 18 19]]]


In [9]:
# Slice the Alternate columns starting from 1st column 
# from the array from Dim 1
# Dimension: 1, Row: All, Columns: all, skip by 2

print(arr3d[1,:,::2])

[[11 13 15]
 [16 18 20]]


In [10]:
# Slice the 1st, 4th  & 5th columns from arry
# Dimension: All, Row: All, Columns: 0, 3 & 4 

print(arr3d[:,:,[0,3,4]])

[[[ 1  4  5]
  [ 6  9 10]]

 [[11 14 15]
  [16 19 20]]]


In [11]:
# Display only Even Numbers
arr3d % 2 ==0

array([[[False,  True, False,  True, False],
        [ True, False,  True, False,  True]],

       [[False,  True, False,  True, False],
        [ True, False,  True, False,  True]]])

In [12]:
# Condition - Only even numbers

arr3d[arr3d % 2 ==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int8)

In [13]:
# Multiple filter criterias
# Even numbers and Less than 10

arr3d[(arr3d % 2 ==0) & (arr3d <10) ]

array([2, 4, 6, 8], dtype=int8)


***
