In [2]:
import numpy as np

In [3]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [4]:
arr1

array([[0.2816748 , 0.02775001, 0.00870231, 0.25807858],
       [0.80326444, 0.96653376, 0.30379143, 0.98084715],
       [0.02566321, 0.03450475, 0.1920311 , 0.98080313]])

In [5]:
arr2

array([[0.80514966, 0.88101329, 0.72233573, 0.06338669],
       [0.19944256, 0.15100534, 0.58728863, 0.4756726 ],
       [0.6678126 , 0.72342471, 0.72400987, 0.87000761]])

In [6]:
arr1 + arr2

array([[1.08682446, 0.90876329, 0.73103803, 0.32146527],
       [1.002707  , 1.1175391 , 0.89108006, 1.45651975],
       [0.69347582, 0.75792946, 0.91604097, 1.85081074]])

In [7]:
arr1 - arr2

array([[-0.52347486, -0.85326328, -0.71363342,  0.1946919 ],
       [ 0.60382189,  0.81552842, -0.2834972 ,  0.50517456],
       [-0.64214939, -0.68891997, -0.53197876,  0.11079552]])

In [8]:
arr1 * arr2

array([[0.22679037, 0.02444812, 0.00628599, 0.01635875],
       [0.16020511, 0.14595176, 0.17841325, 0.46656211],
       [0.01713822, 0.02496159, 0.13903241, 0.85330618]])

In [9]:
arr1 / arr2

array([[0.34984155, 0.03149783, 0.01204745, 4.07149498],
       [4.02754788, 6.40065936, 0.5172779 , 2.06202157],
       [0.03842876, 0.04769639, 0.26523271, 1.12735006]])

In [10]:
np.exp(arr1)

array([[1.32534765, 1.02813862, 1.00874028, 1.29444054],
       [2.23281795, 2.62881654, 1.35498642, 2.6667144 ],
       [1.02599535, 1.03510694, 1.2117082 , 2.666597  ]])

In [11]:
np.log(np.exp(arr1))

array([[0.2816748 , 0.02775001, 0.00870231, 0.25807858],
       [0.80326444, 0.96653376, 0.30379143, 0.98084715],
       [0.02566321, 0.03450475, 0.1920311 , 0.98080313]])

In [12]:
np.sin(arr1)

array([[0.27796484, 0.02774644, 0.0087022 , 0.25522324],
       [0.71962662, 0.8229213 , 0.29914016, 0.83096896],
       [0.0256604 , 0.0344979 , 0.19085305, 0.83094446]])

In [13]:
np.cos(arr1)

array([[0.96059125, 0.99961499, 0.99996214, 0.96688215],
       [0.69436123, 0.56815538, 0.95420918, 0.55631879],
       [0.99967072, 0.99940477, 0.98161862, 0.55635537]])

In [14]:
np.sqrt(arr1)

array([[0.53073044, 0.16658333, 0.09328615, 0.50801435],
       [0.89625021, 0.98312449, 0.55117278, 0.99037728],
       [0.16019742, 0.18575453, 0.43821353, 0.99035505]])

In [15]:
arr_inv = 1 / arr1

In [16]:
arr_inv

array([[  3.55019334,  36.03602922, 114.91208218,   3.87478876],
       [  1.24492004,   1.03462501,   3.2917321 ,   1.01952684],
       [ 38.96628128,  28.9815197 ,   5.20748978,   1.0195726 ]])

In [17]:
arr1 = np.zeros((3, 5))

In [18]:
arr_inv = 1/arr1

C:\Users\i025736\AppData\Local\Temp/ipykernel_22804/2508733167.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_inv = 1/arr1


In [19]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [20]:
np.isinf(arr_inv[0,0])

True

In [21]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])


***
