
# Numpy - Operations - Arrary Copy


In [1]:
import numpy as np


****



## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [2]:
# Make a copy, change the original array, and display both arrays
# The changes do not reflect in the copied version

arr3 = np.array([1, 2, 3, 4, 5])
copy_arr3 = arr3.copy()
arr3[0] = 42

print("Original:\n",arr3)
print("Copied Version:\n",copy_arr3)

Original:
 [42  2  3  4  5]
Copied Version:
 [1 2 3 4 5]


In [3]:
# Make a View, change the original array, and display both arrays
# The changes do not reflect in the copied version

arr4 = np.array([1, 2, 3, 4, 5])
view_arr4 = arr4.view()
arr4[[1, -1]] = 42

print("Original:\n",arr4)
print("View Version:\n",view_arr4)

Original:
 [ 1 42  3  4 42]
View Version:
 [ 1 42  3  4 42]



### Check if Array Owns it's Data

Every NumPy array has the attribute base that returns `None` if the array owns the data. Otherwise, the base  attribute refers to the original object.

In [4]:
print(copy_arr3.base, view_arr4.base)

None [ 1 42  3  4 42]



****
