
# Numpy - Operations - Reshape


In [2]:
import numpy as np


****



## Reshape of an Array

Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions or change number of elements in each dimension.

As long as the elements required for reshaping are equal in both shapes. We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [2]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshape_arr5 = arr5.reshape(4, 3)

print("Original:\n",arr5)
print("Reshaped Array:\n",reshape_arr5)

Original:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
# Check if the returned array is a copy or a view
# Reshape a view of orginal array
# Hence to be careful while doing any changes

print(reshape_arr5.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
# Standard method to reshape

x = np.array([1, 2, 3])
print("x Shape before reshape {0}".format(x.shape))
x_reshape = x.reshape((1, 3))
print("x Shape after reshape {0}".format(x_reshape.shape))

x Shape before reshape (3,)
x Shape after reshape (1, 3)


In [18]:
# newaxis method with a slice operation

x = np.array([1, 2, 3])
print("x Shape before reshape {0}".format(x.shape))
x_reshape = x[np.newaxis, :]
print("x Shape after reshape {0}".format(x_reshape.shape))

x Shape before reshape (3,)
x Shape after reshape (1, 3)


In [20]:
# newaxis method with a slice operation

x = np.array([1, 2, 3])
print("x Shape before reshape {0}".format(x.shape))
x_reshape = x[:, np.newaxis]
print("x Shape after reshape {0}".format(x_reshape.shape))
print(x_reshape)

x Shape before reshape (3,)
x Shape after reshape (3, 1)
[[1]
 [2]
 [3]]


In [37]:
x = np.arange(1, 13).reshape(3,4)
x_reshape1 = x[np.newaxis,:]
print(x.shape)
print(x_reshape1.shape)
print(x_reshape1)


(3, 4)
(1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [38]:
x = np.arange(1, 13).reshape(3,4)
x_reshape2 = x[:,np.newaxis,:]
print(x.shape)
print(x_reshape2.shape)
print(x_reshape2)


(3, 4)
(3, 1, 4)
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [40]:
x = np.arange(1, 13).reshape(3,4)
x_reshape3 = x[:,:,np.newaxis]
print(x.shape)
print(x_reshape3.shape)
print(x_reshape3)


(3, 4)
(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]



### Unknown Dimension

You are allowed to have one "unknown" dimension. Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [4]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshape_arr6 = arr5.reshape(2, 2, -1)

print("Original:\n",arr6)
print("\nReshaped Array:\n",reshape_arr6)
print("\nShare of the Array:", reshape_arr6.shape)

Original:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Share of the Array: (2, 2, 3)



### Flattening the Array

Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [5]:
arr7 = np.array([[1, 2, 3], [4, 5, 6]])
arr_flat = arr7.reshape(-1)

print("Original:\n",arr7)
print("\nReshaped Array:\n", arr_flat)
print("\nShape of the Array:", arr_flat.shape)

Original:
 [[1 2 3]
 [4 5 6]]

Reshaped Array:
 [1 2 3 4 5 6]

Shape of the Array: (6,)


In [6]:
arr8 = np.array([[1, 2, 3], [4, 5, 6]])
arr_flatten = arr8.flatten()

print("Original:\n",arr8)
print("\nReshaped Array:\n", arr_flatten)
print("\nShape of the Array:", arr_flatten.shape)

Original:
 [[1 2 3]
 [4 5 6]]

Reshaped Array:
 [1 2 3 4 5 6]

Shape of the Array: (6,)


In [7]:
arr9 = np.array([[1, 2, 3], [4, 5, 6]])
arr_ravel = np.ravel(arr9)

print("Original:\n",arr9)
print("\nReshaped Array:\n", arr_ravel)
print("\nShape of the Array:", arr_flatten.shape)

Original:
 [[1 2 3]
 [4 5 6]]

Reshaped Array:
 [1 2 3 4 5 6]

Shape of the Array: (6,)


In [8]:
# Rotate an array by 90 degrees in the plane specified by axes.
# Rotation direction is from the first towards the second axis.

arr10 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original :\n", arr10)
print("\nRotate 90:\n",np.rot90(arr10))
print("\nRotate 90:\n",np.rot90(arr10, 1))
print("\nAnother 90 (180):\n",np.rot90(arr10, 2))
print("\nAnother 90 (270):\n",np.rot90(arr10, 3))
print("\nAnother 90 (360 - Original):\n",np.rot90(arr10, 4))


Original :
 [[1 2 3]
 [4 5 6]]

Rotate 90:
 [[3 6]
 [2 5]
 [1 4]]

Rotate 90:
 [[3 6]
 [2 5]
 [1 4]]

Another 90 (180):
 [[6 5 4]
 [3 2 1]]

Another 90 (270):
 [[4 1]
 [5 2]
 [6 3]]

Another 90 (360 - Original):
 [[1 2 3]
 [4 5 6]]


In [9]:
arr11 = np.array([[[1, 2, 3], [4, 5, 6]],[[7,8,9],[10,11,12]]])
print("Original:\n",arr11)
print("\nRotated with Axes:\n", np.rot90(arr11, 1, (2, 1)))

Original:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Rotated with Axes:
 [[[ 4  1]
  [ 5  2]
  [ 6  3]]

 [[10  7]
  [11  8]
  [12  9]]]


Reverse the order of elements in an array along the given axis. The shape of the array is preserved, but the elements are reordered.

In [10]:
arr12 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n",arr12)
print("\n Flip Array:\n", np.flip(arr12))
print("\n Flip Array:\n", np.flip(arr12, 1))

Original:
 [[1 2 3]
 [4 5 6]]

 Flip Array:
 [[6 5 4]
 [3 2 1]]

 Flip Array:
 [[3 2 1]
 [6 5 4]]


Reverse the order of elements along axis 1 (left/right). For a 2-D array, this flips the entries in each row in the left/right direction. Columns are preserved, but appear in a different order than before.

In [11]:
arr13 = np.diag([1,2,3,4])
print("Original\n", arr13)
print("Fliplr:\n", np.fliplr(arr13))

Original
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Fliplr:
 [[0 0 0 1]
 [0 0 2 0]
 [0 3 0 0]
 [4 0 0 0]]


Reverse the order of elements along axis 0 (up/down). For a 2-D array, this flips the entries in each column in the up/down direction. Rows are preserved, but appear in a different order than before

In [12]:
arr14 = np.array([[[1, 2, 3], [4, 5, 6]],[[7,8,9],[10,11,12]]])
np.flipud(arr14)

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [13]:
arr15 = np.array([[1, 2, 3], [4, 5, 6]])
np.flipud(arr15)

array([[4, 5, 6],
       [1, 2, 3]])


****
