In [1]:
import numpy as np


***


## NumPy - Array Iteration

Iterating means going through elements one by one.As we deal with multi-dimensional arrays in numpy, we can do this using basic `for loop` of python.

If we iterate on a 
* 1-D array it will go through each element one by one.
* 2-D array it will go through all the rows.
* 3-D array it will go through all the 2-D arrays.

If we iterate on a n-D array it will go through n-1th dimension one by one.

### Iterating a 1-D Array

In [2]:
# Iterating a 1-D array

arr1d = np.array([1, 2, 3])

for x in arr1d:
  print(x)


1
2
3



### Iterating a 2-D Array

In [3]:
# Iterating 2-D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr2d:
  print(x)

[1 2 3]
[4 5 6]


In [4]:
# To go to the element level
# Pass x as arry to next level

arr2d = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr2d:
    for y in x:
        print(y)

1
2
3
4
5
6



### Iterating a 3-D Array


In [5]:
# Iterating a 3-D Array

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr3d:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
# To go to row level - pass it to second level

for x in arr3d:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [7]:
# To go to element level pass to the next level

for x in arr3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12



****



## Iterating Arrays using nditer()

The function `nditer()` is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [8]:
# Iterating a 3-D Array at scalar level

arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr3d):
  print(x)

1
2
3
4
5
6
7
8


In [9]:
# Iterating a 2-D array at scalar level.
arr2d = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr2d):
  print(x)

1
2
3
4



****



## Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

Parameter op_dtypes controls what kind of data casting may occur when making a copy or buffering. setting this to `unsafe` is not recommended, as it can adversely affect accumulations. Default setting is `safe`

* 'no' means the data types should not be cast at all.
* 'equiv' means only byte-order changes are allowed.
* 'safe' means only casts which can preserve values are allowed.
* 'same_kind' means only safe casts or casts within a kind, like float64 to float32, are allowed.
* 'unsafe' means any data conversions may be done.


In [10]:
# nditer allows only safe casting by default

arr2d = np.array([[1, 2], [3, 4]])
print("Data Type of Array:", arr2d.dtype)

print("\nCasting done to int64")
for x in np.nditer(arr2d, flags=['buffered'], 
                   op_dtypes=['i8']):
  print(x)

print("\nCasting done to float (unsafe)")
for x in np.nditer(arr2d, flags=['buffered'], 
                   op_dtypes=['f'], casting='unsafe'):
  print(x)

Data Type of Array: int32

Casting done to int64
1
2
3
4

Casting done to float (unsafe)
1.0
2.0
3.0
4.0



****


### Iterating With Different Step Size

We can use filtering and followed by iteration. 

In [11]:
# Iterate through every scalar element of the 2D array 
# skipping 1 element

arr2d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

for x in np.nditer(arr2d[:, ::2]):
  print(x)


1
3
5
7
9
11



****


## Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one. Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases.

In [12]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr2d):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8



***
