
# NumPy - Joining Arrays


In [1]:
import numpy as np

----

## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as `0`.

**Note:** To join both array in specific axis, that dimention should exist before.

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

Array 1:
 [1 2 3]

Array 2:
 [4 5 6]


In [3]:
# Join the array using axis 0 - Horizontal Stack

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


#### Joining 2-D Array

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=0)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)


Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Joined Array : (4, 2) Dimentions: 2
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=1)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Joined Array : (2, 4) Dimentions: 2
[[ 1  2 11 12]
 [ 3  4 13 14]]


## Joining a 3-D Array

In [6]:
arr1 = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
arr2 = np.array([[[11, 12], [13, 14]],[[15, 16],[17, 18]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
arr = np.concatenate((arr1, arr2), axis=0)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 2) Dimensions: 3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape of Array 2: (2, 2, 2) Dimensions: 3
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]

Joined Array : (4, 2, 2) Dimentions: 3
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [7]:
arr1 = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 12], [13, 14]],[[15, 16],[17, 18]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=1)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 2) Dimensions: 3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape of Array 2: (2, 2, 2) Dimensions: 3
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]

Joined Array : (2, 4, 2) Dimentions: 3
[[[ 1  2]
  [ 3  4]
  [11 12]
  [13 14]]

 [[ 5  6]
  [ 7  8]
  [15 16]
  [17 18]]]


In [8]:
arr1 = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 12], [13, 14]],[[15, 16],[17, 18]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.concatenate((arr1, arr2), axis=2)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 2) Dimensions: 3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape of Array 2: (2, 2, 2) Dimensions: 3
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]

Joined Array : (2, 2, 4) Dimentions: 3
[[[ 1  2 11 12]
  [ 3  4 13 14]]

 [[ 5  6 15 16]
  [ 7  8 17 18]]]



----


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a **new axis**.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [9]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

print("\nArray 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
print("\nArray 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
print("\nArray 3:",arr3.shape, "Dimensions:", arr3.ndim)
print(arr3)

arr = np.stack((arr1, arr2, arr3), axis=0)
print("\nStacked Arrays:",arr.shape, "Dimensions:", arr.ndim)
print(arr)


Array 1: (2,) Dimensions: 1
[1 2]

Array 2: (2,) Dimensions: 1
[3 4]

Array 3: (2,) Dimensions: 1
[5 6]

Stacked Arrays: (3, 2) Dimensions: 2
[[1 2]
 [3 4]
 [5 6]]


In [10]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

print("\nArray 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
print("\nArray 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
print("\nArray 3:",arr3.shape, "Dimensions:", arr3.ndim)
print(arr3)

arr = np.stack((arr1, arr2, arr3), axis=1)
print("\nStacked Arrays:",arr.shape, "Dimensions:", arr.ndim)
print(arr)


Array 1: (2,) Dimensions: 1
[1 2]

Array 2: (2,) Dimensions: 1
[3 4]

Array 3: (2,) Dimensions: 1
[5 6]

Stacked Arrays: (2, 3) Dimensions: 2
[[1 3 5]
 [2 4 6]]



### Stacking a 2-D Arrays


In [11]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=0)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Joined Array : (2, 2, 2) Dimentions: 3
[[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]


In [12]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=1)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Joined Array : (2, 2, 2) Dimentions: 3
[[[ 1  2]
  [11 12]]

 [[ 3  4]
  [13 14]]]


In [13]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=2)
print("\nJoined Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Joined Array : (2, 2, 2) Dimentions: 3
[[[ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]]]


### Stacking a 3-D Arrays

In [14]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=0)
print("\nStacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Stacked Array : (2, 2, 2, 3) Dimentions: 4
[[[[  1   2   3]
   [  3   4   5]]

  [[  6   7   8]
   [  9  10  11]]]


 [[[ 11  21  31]
   [ 31  41  51]]

  [[ 61  71  81]
   [ 91 101 111]]]]


In [15]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=1)
print("\nStacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Stacked Array : (2, 2, 2, 3) Dimentions: 4
[[[[  1   2   3]
   [  3   4   5]]

  [[ 11  21  31]
   [ 31  41  51]]]


 [[[  6   7   8]
   [  9  10  11]]

  [[ 61  71  81]
   [ 91 101 111]]]]


In [16]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=2)
print("\nStacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Stacked Array : (2, 2, 2, 3) Dimentions: 4
[[[[  1   2   3]
   [ 11  21  31]]

  [[  3   4   5]
   [ 31  41  51]]]


 [[[  6   7   8]
   [ 61  71  81]]

  [[  9  10  11]
   [ 91 101 111]]]]


In [17]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.stack((arr1, arr2), axis=3)
print("\nStacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Stacked Array : (2, 2, 3, 2) Dimentions: 4
[[[[  1  11]
   [  2  21]
   [  3  31]]

  [[  3  31]
   [  4  41]
   [  5  51]]]


 [[[  6  61]
   [  7  71]
   [  8  81]]

  [[  9  91]
   [ 10 101]
   [ 11 111]]]]


---


## Stacking Along Rows

NumPy provides a helper function: `hstack()` to stack along rows.

#### Stacking 1-D Array

In [18]:

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

print("\nArray 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
print("\nArray 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
print("\nArray 3:",arr3.shape, "Dimensions:", arr3.ndim)
print(arr3)

arr = np.hstack((arr1, arr2, arr3))
print("\n Horizontaly Stacked Arrays:",arr.shape, "Dimensions:", arr.ndim)
print(arr)


Array 1: (2,) Dimensions: 1
[1 2]

Array 2: (2,) Dimensions: 1
[3 4]

Array 3: (2,) Dimensions: 1
[5 6]

 Horizontaly Stacked Arrays: (6,) Dimensions: 1
[1 2 3 4 5 6]


#### Stacking 2-D Array

In [19]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.hstack((arr1, arr2))
print("\nHorizontaly Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Horizontaly Stacked Array : (2, 4) Dimentions: 2
[[ 1  2 11 12]
 [ 3  4 13 14]]


#### Stacking 3-D Array

In [27]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.hstack((arr1, arr2))
print("\nHorizontally Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Horizontally Stacked Array : (2, 4, 3) Dimentions: 3
[[[  1   2   3]
  [  3   4   5]
  [ 11  21  31]
  [ 31  41  51]]

 [[  6   7   8]
  [  9  10  11]
  [ 61  71  81]
  [ 91 101 111]]]



***



## Stacking Along Columns

NumPy provides a helper function: `vstack()`  to stack along columns.

#### Stacking 1-D Array

In [21]:

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

print("\nArray 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
print("\nArray 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
print("\nArray 3:",arr3.shape, "Dimensions:", arr3.ndim)
print(arr3)

arr = np.vstack((arr1, arr2, arr3))
print("\nVertical Stacked Arrays:",arr.shape, "Dimensions:", arr.ndim)
print(arr)


Array 1: (2,) Dimensions: 1
[1 2]

Array 2: (2,) Dimensions: 1
[3 4]

Array 3: (2,) Dimensions: 1
[5 6]

Vertical Stacked Arrays: (3, 2) Dimensions: 2
[[1 2]
 [3 4]
 [5 6]]


#### Stacking 2-D Array

In [22]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.vstack((arr1, arr2))
print("\nVertical Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Vertical Stacked Array : (4, 2) Dimentions: 2
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]


#### Stacking 3-D Array

In [23]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.vstack((arr1, arr2))
print("\nVertical Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Vertical Stacked Array : (4, 2, 3) Dimentions: 3
[[[  1   2   3]
  [  3   4   5]]

 [[  6   7   8]
  [  9  10  11]]

 [[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]



---



## Stacking Along Height (depth)

NumPy provides a helper function: `dstack()` to stack along height, which is the same as depth.

#### Stacking 1-D Array

In [24]:

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

print("\nArray 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)
print("\nArray 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)
print("\nArray 3:",arr3.shape, "Dimensions:", arr3.ndim)
print(arr3)

arr = np.dstack((arr1, arr2, arr3))
print("\nDepth Stacked Arrays:",arr.shape, "Dimensions:", arr.ndim)
print(arr)


Array 1: (2,) Dimensions: 1
[1 2]

Array 2: (2,) Dimensions: 1
[3 4]

Array 3: (2,) Dimensions: 1
[5 6]

Depth Stacked Arrays: (1, 2, 3) Dimensions: 3
[[[1 3 5]
  [2 4 6]]]


#### Stacking 2-D Array

In [25]:
arr1 = np.array([[1, 2], [3, 4]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[11, 12], [13, 14]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.dstack((arr1, arr2))
print("\nDepth Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2) Dimensions: 2
[[1 2]
 [3 4]]

Shape of Array 2: (2, 2) Dimensions: 2
[[11 12]
 [13 14]]

Depth Stacked Array : (2, 2, 2) Dimentions: 3
[[[ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]]]


#### Stacking 3-D Array

In [26]:
arr1 = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print("Shape of Array 1:",arr1.shape, "Dimensions:", arr1.ndim)
print(arr1)

arr2 = np.array([[[11, 21, 31], [31, 41, 51]],[[61, 71, 81],[91, 101, 111]]])
print("\nShape of Array 2:",arr2.shape, "Dimensions:", arr2.ndim)
print(arr2)

arr = np.dstack((arr1, arr2))
print("\nDepth Stacked Array :", arr.shape, "Dimentions:", arr.ndim)
print(arr)

Shape of Array 1: (2, 2, 3) Dimensions: 3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Shape of Array 2: (2, 2, 3) Dimensions: 3
[[[ 11  21  31]
  [ 31  41  51]]

 [[ 61  71  81]
  [ 91 101 111]]]

Depth Stacked Array : (2, 2, 6) Dimentions: 3
[[[  1   2   3  11  21  31]
  [  3   4   5  31  41  51]]

 [[  6   7   8  61  71  81]
  [  9  10  11  91 101 111]]]



---
