In [1]:
import numpy as np


-------



# NumPy - Linear Algebra


 **Dot product of two arrays. Specifically,**
- If both `a` and `b` are 1-D arrays, it is inner product of vectors (without complex conjugation).
- If both `a` and `b` are 2-D arrays, it is matrix multiplication, but using :func:`matmul` or ``a @ b`` is preferred.
- If either `a` or `b` is 0-D (scalar), it is equivalent to func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over the last axis of `a` and `b`.
- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a sum product over the last axis of `a` and the second-to-last axis of `b`

In [12]:
# a and b are 1-D Array
a = np.array([1,2,3])
b = np.array([5,6,7])
np.dot(a, b)

38

In [13]:
# Dot Product of 2 Arrays
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [15]:
a = np.array([[1,2],[3,4]])
b = np.array(5)
np.dot(a, b)

array([[ 5, 10],
       [15, 20]])

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([2,2])
np.dot(a, b)

array([ 6, 14])

In [30]:
# Dot Product of N x M D array

a = np.array([[1, 2, 3],[4, 5, 6]]) 
b = np.array([[2, 1],[2, 2],[2, 3]]) 

np.dot(a,b)

array([[12, 14],
       [30, 32]])

##### Matrix Multiplication

In [34]:
a = np.array([[1, 2, 3],[4, 5, 6]]) 
b = np.array([[2, 1],[2, 2],[2, 3]]) 
np.matmul(a,b)

array([[12, 14],
       [30, 32]])

#### Dot product of the two vectors.

In [35]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.vdot(a,b)

130

#### Determinant of Matrix

In [41]:
a = np.array([[11, 2, 3],[14, 5, 6],[7,18,9]]) 
np.linalg.det(a)

-209.99999999999977

In [43]:
a = np.array([[1,2], [3,4]]) 
b = np.array([[11, 12], [13, 14]]) 
np.inner(a,b)

array([[35, 41],
       [81, 95]])

#### 

In [46]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [48]:
# Check that the solution is correct:
np.allclose(np.dot(a, x), b)


True

In [52]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])