In [1]:
import numpy as np


-----


In [2]:
scores = np.loadtxt("cric_data.txt", 
                   skiprows=1,
                   usecols=(1,2,3))

In [3]:
scores.shape

(225, 3)

In [4]:
sachin = scores[:,0]
rahul =  scores[:,1]
india =  scores[:,2]

### Questions

1. Find mean, median, IQR for Sachin, Rahul, and India
2. Find the histogram of Sachin's scores with 10 bins
3. Find mean of Sachin's scores grouped by 25 matches
4. Find mean of Sachin's scores where he has scored a century
5. Find mean of Sachin's scores when Rahul has scored less than 10
6. Find mean for Sachin's scores based on which quartile India's score falls in
7. For every match find out who has has scored more - Sachin or Rahul
8. How many more runs does Sachin score on average after having scored x runs
9. How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...

#### 1. Find mean, median, IQR for Sachin, Rahul, and India

In [5]:
mean = np.mean(scores, axis=0)
median = np.median(scores, axis=0)
iqr =np.percentile(scores ,[25, 75], axis=0)

print("Mean Score of Sachin:{0}, Rahul:{1}, India:{2}".format(mean[0],mean[1],mean[2]))
print("Median Score of Sachin:{0}, Rahul:{1}, India:{2}".format(median[0],median[1],median[2]))
print("IQR for Sachin:{0}, Rahul:{1}, India:{2}".format((iqr[1,0] - iqr[0,0]),(iqr[1,1] - iqr[0,1]), iqr[1,2] - iqr[0,2]))

Mean Score of Sachin:39.87555555555556, Rahul:32.062222222222225, India:220.79555555555555
Median Score of Sachin:27.0, Rahul:22.0, India:216.0
IQR for Sachin:57.0, Rahul:46.0, India:98.0


#### 2. Find the histogram of Sachin's scores with 10 bins

In [6]:
np.histogram(sachin, bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

#### 3. Find mean of Sachin's scores grouped by 25 matches

In [7]:
arr = np.split(sachin ,len(sachin)/25)
print(np.mean(arr, axis=1))  

[33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


In [8]:
# Professor Solution

sachin_reshape = sachin.reshape(9, 25)
print(np.mean(sachin_reshape , axis=1))

[33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


#### 4. Find mean of Sachin's scores where he has scored a century


In [9]:
np.mean(sachin[sachin>=100])

125.0

#### 5. Find mean of Sachin's scores when Rahul has scored less than 10

In [10]:
np.mean(sachin[rahul<10])

40.74285714285714

#### 6. Find mean for Sachin's scores based on which quartile India's score falls in

In [11]:
ind_irq = np.percentile(india, [25, 50, 75, 100])
print(ind_irq)

[175. 216. 273. 499.]


In [12]:
print("Sachin mean for India Quartile 1: {}"
      .format(np.mean(sachin[india<=ind_irq[0]])))
print("Sachin mean for India Quartile 2: {}"
      .format(np.mean(sachin[(india>ind_irq[0]) & (india<=ind_irq[1])])))
print("Sachin mean for India Quartile 3: {}"
.format(np.mean(sachin[(india>ind_irq[1]) & (india<=ind_irq[2])])))
print("Sachin mean for India Quartile 4: {}"
.format(np.mean(sachin[(india>ind_irq[2]) & (india<=ind_irq[3])])))

Sachin mean for India Quartile 1: 20.912280701754387
Sachin mean for India Quartile 2: 35.07142857142857
Sachin mean for India Quartile 3: 40.482142857142854
Sachin mean for India Quartile 4: 63.375


#### 7. For every match find out who has has scored more - Sachin or Rahul

In [13]:
is_sachin_higher = np.argmax(scores[:,[0,1]], axis=1)

In [14]:
np.where(is_sachin_higher == 1, "Rahul","Sachin")

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

#### 8. How many more runs does Sachin score on average after having scored x runs

In [22]:
for i in range(0, int(np.max(sachin)), 10):
    print("Sachin Already Scored {0} Runs, Expected to score {1} more Runs." 
         .format(i, int(np.mean(sachin[sachin >= i])) - i))

Sachin Already Scored 0 Runs, Expected to score 39 more Runs.
Sachin Already Scored 10 Runs, Expected to score 47 more Runs.
Sachin Already Scored 20 Runs, Expected to score 46 more Runs.
Sachin Already Scored 30 Runs, Expected to score 45 more Runs.
Sachin Already Scored 40 Runs, Expected to score 44 more Runs.
Sachin Already Scored 50 Runs, Expected to score 43 more Runs.
Sachin Already Scored 60 Runs, Expected to score 38 more Runs.
Sachin Already Scored 70 Runs, Expected to score 37 more Runs.
Sachin Already Scored 80 Runs, Expected to score 30 more Runs.
Sachin Already Scored 90 Runs, Expected to score 27 more Runs.
Sachin Already Scored 100 Runs, Expected to score 25 more Runs.
Sachin Already Scored 110 Runs, Expected to score 23 more Runs.
Sachin Already Scored 120 Runs, Expected to score 18 more Runs.
Sachin Already Scored 130 Runs, Expected to score 17 more Runs.
Sachin Already Scored 140 Runs, Expected to score 9 more Runs.
Sachin Already Scored 150 Runs, Expected to score 19

#### 9. How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...

In [16]:
sachin_t = np.add.accumulate(sachin)
np.histogram(sachin_t, bins=np.arange(0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int64),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

In [17]:
## Professor Vesion
sachin_cumscores = np.cumsum(sachin)
np.histogram(sachin_cumscores, bins=np.arange(0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int64),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))